name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     # Étape 1 : Récupérer le code source
      - name : Checkout code
        uses: actions/checkout@v4

     # Étape 2 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
     

     # Étape 3 : Construire l'image Docker
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag project-meteor:$(date +%s)

      # Étape 4 : Pousser l'image vers Docker Hub
      - name: Push Docker Image
        run: docker push spottier88/project-meteor:latest
