name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     # Étape 1 : Récupérer le code source
      - name : Checkout code
        uses: actions/checkout@v4

     # Étape 2 : Définir une variable pour le tag
      - name: Set dynamic tag
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

     # Étape 3 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
     
     # Étape 4 : Construire l'image Docker
      - name: Build the Docker image
        run: docker build --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/project-meteor:latest .

      # Étape 5 : Vérification des images Docker locales
      - name: List Docker Images
        run: docker images

      # Étape 6 : Pousser l'image vers Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/project-meteor:latest

      #Etape 7 : Tage avec la version
      - name : Tat avec la version
        run : |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/project-meteor:latest \
                     ${{ secrets.DOCKERHUB_USERNAME }}/project-meteor:${{ env.TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/project-meteor:${{ env.TAG }}
